server:
  port: 9097
  
 
spring:
    application:
      name: API-GATEWAY
    cloud:
       gateway:
        routes:
        - id: currency-exchange
          uri: http://localhost:9090
          predicates:
            - Path=/api/currency-exchange/**
        - id: currency-conversion
          uri: http://localhost:9095
          predicates:
            - Path=/api/currency-conversion/**